#!/bin/bash




### Un-Link .RC Files

# ZProfile
rm ~/.zprofile

# Oh-My-Zsh
rm ~/.zshrc

# VIM
rm ~/.vimrc
rm ~/.vim
rm ~/.gvimrc
rm ~/.gvim

# NODE
rm ~/.noderc

# Tig Pager
rm ~/.tigrc

# JSHint
rm ~/.jshintrc
